# Generated by Django 5.1.1 on 2024-09-12 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('id_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='members.member')),
            ],
        ),
    ]
